- DM 10th Algorithm    
  C4.5 Decision Tree, K-mean, SVM, Apriori, EM, PageRank, AdaBoost, KNN, Naive Bayes,CART

- 為什麼要使用統計學？   
  因為在現實世界中，我們無法使用精確的數學模型，來判別人類行為和思想，因此需要統計學的幫助。

- 如何從海量數據中抽取到有價值的信息是一個非常重要的課題

- 現今的工作類似於：最大化利潤、最小化風險、找到最好的市場策略

- 使用鳥類專家的例子來帶入feature, classification, training set, testing set

- 監督學習：
  K-NN, Naive Bayes classifier, SVM, Decision Tree, Linear Regression, Locally Weighted Linear Regression, Ridge, Lasso
- 無監督學習：
  K-mean, DBSCAN, EM, Parzen

- 主要需要了解：    
  特徵值是離散型變數還是連續型變數、特徵值中是否存在遺失值、為何有遺失值（原因）、是否有離群值、某個特徵發生的頻率如何

In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[0.46327179, 0.17069736, 0.53303374, 0.66971448],
       [0.90672927, 0.80831828, 0.25837841, 0.33172634],
       [0.2188115 , 0.28772135, 0.28754157, 0.16008404],
       [0.51873643, 0.08659432, 0.62799188, 0.26504936]])

In [3]:
randMat = mat(random.rand(4,4))
print(randMat.I)

[[ 0.26244953 -0.05231811 -1.61009352  1.28004421]
 [-0.10385477  1.50976892  0.39391622 -0.44169088]
 [ 2.36217843 -0.92182967 -2.52690763  0.02193393]
 [-1.52955999 -0.33992199  3.38269446  0.09478732]]


In [4]:
invRandMat = randMat.I
print(randMat * invRandMat)

[[ 1.00000000e+00  2.73288333e-17  4.92268602e-16  2.99423028e-19]
 [ 1.79016356e-17  1.00000000e+00  5.11060779e-17 -1.40637309e-17]
 [-7.76469386e-17  4.38766594e-17  1.00000000e+00 -1.24688775e-17]
 [ 2.18175163e-17  3.68975558e-17  2.04365565e-16  1.00000000e+00]]


In [5]:
myEye = randMat * invRandMat
print(myEye - eye(4))

[[-2.22044605e-16  2.73288333e-17  4.92268602e-16  2.99423028e-19]
 [ 1.79016356e-17  0.00000000e+00  5.11060779e-17 -1.40637309e-17]
 [-7.76469386e-17  4.38766594e-17  2.22044605e-16 -1.24688775e-17]
 [ 2.18175163e-17  3.68975558e-17  2.04365565e-16 -1.11022302e-16]]


In [6]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])